apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  template:
    spec:
      containers:
      - name: profile-controller
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-secrets
              key: aws-access-key-id
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-secrets
              key: aws-secret-access-key