apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: auth
spec:
  template:
    spec:
      containers:
        - name: dex
          envFrom:
            - secretRef:
                name: dex-sso-secret
            - secretRef:
                name: dex-oidc-client
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: dex-config
          name: config
