apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authservice
  namespace: istio-system
spec:
  template:
    spec:
      containers:
        - name: authservice
          env:
          - name: OIDC_PROVIDER
            valueFrom:
              secretKeyRef:
                name: authservice-sso-secret
                key: OIDC_PROVIDER
