apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubeflow/manifests//common/cert-manager/kubeflow-issuer/base?ref=v1.4.0
- https://github.com/kubeflow/manifests//common/oidc-authservice/base?ref=v1.4.0
- https://github.com/kubeflow/manifests//common/dex/overlays/istio?ref=v1.4.0
- https://github.com/kubeflow/manifests//common/kubeflow-namespace/base?ref=v1.4.0
- https://github.com/kubeflow/manifests//common/kubeflow-roles/base?ref=v1.4.0
- https://github.com/kubeflow/manifests//common/istio-1-9/kubeflow-istio-resources/base?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/pipeline/upstream/env/platform-agnostic-multi-user?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/centraldashboard/upstream/overlays/istio?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/admission-webhook/upstream/overlays/cert-manager?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/jupyter/jupyter-web-app/upstream/overlays/istio?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/jupyter/notebook-controller/upstream/overlays/kubeflow?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/profiles/upstream/overlays/kubeflow?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/volumes-web-app/upstream/overlays/istio?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow?ref=v1.4.0
- https://github.com/kubeflow/manifests//apps/tensorboard/tensorboards-web-app/upstream/overlays/istio?ref=v1.4.0
- https://github.com/kubeflow/manifests//common/user-namespace/base?ref=v1.4.0
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: cloud-kubeflow-pipelines-profile-controller-code
  files:
  - sync.py
patchesStrategicMerge:
- patches/cloud-profile-controller-patch.yaml
- patches/dex-patch.yaml
- patches/cloud-metadata-patch.yaml
- patches/cloud-workflow-controller-deployment-patch.yaml
- patches/oidc-authservice-patch.yaml
- patches/cloud-pipeline-patch.yaml
- patches/cloud-cache-patch.yaml
- patches/minio-gateway-patch.yaml

images:
- name: minio
  newName: minio/minio
  newTag: RELEASE.2021-10-13T00-23-17Z

patches:
- target:
    kind: ConfigMap
    name: workflow-controller-configmap
  patch: |-
    - op: replace
      path: /metadata/name
      value: not-used-workflow-controller-configmap
- target:
    kind: ConfigMap
    name: dex
  patch: |-
    - op: replace
      path: /metadata/name
      value: not-used-dex-config
- target:
    kind: Secret
    name: mlpipeline-minio-artifact
  patch: |-
    - op: replace
      path: /metadata/name
      value: not-used-mlpipeline-minio-artifact
