apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
# Cert-Manager
- https://github.com/kubeflow/manifests//common/cert-manager/cert-manager/base
- https://github.com/kubeflow/manifests//common/cert-manager/kubeflow-issuer/base
# Istio
- https://github.com/kubeflow/manifests//common/istio-1-9/istio-crds/base
- https://github.com/kubeflow/manifests//common/istio-1-9/istio-namespace/base
- https://github.com/kubeflow/manifests//common/istio-1-9/istio-install/base
# OIDC Authservice
- https://github.com/kubeflow/manifests//common/oidc-authservice/base
# Dex
- https://github.com/kubeflow/manifests//common/dex/overlays/istio
# # KNative
# - https://github.com/kubeflow/manifests//common/knative/knative-serving/base
# - https://github.com/kubeflow/manifests//common/knative/knative-eventing/base
# - https://github.com/kubeflow/manifests//common/istio-1-9/cluster-local-gateway/base
# Kubeflow namespace
- https://github.com/kubeflow/manifests//common/kubeflow-namespace/base
# Kubeflow Roles
- https://github.com/kubeflow/manifests//common/kubeflow-roles/base
# Kubeflow Istio Resources
- https://github.com/kubeflow/manifests//common/istio-1-9/kubeflow-istio-resources/base


# Kubeflow Pipelines
- https://github.com/kubeflow/manifests//apps/pipeline/upstream/env/platform-agnostic-multi-user
# # KFServing
# - https://github.com/kubeflow/manifests//apps/kfserving/upstream/overlays/kubeflow
# # Katib
# - https://github.com/kubeflow/manifests//apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- https://github.com/kubeflow/manifests//apps/centraldashboard/upstream/overlays/istio
# Admission Webhook
- https://github.com/kubeflow/manifests//apps/admission-webhook/upstream/overlays/cert-manager
# Notebook Controller
- https://github.com/kubeflow/manifests//apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Jupyter Web App
- https://github.com/kubeflow/manifests//apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- https://github.com/kubeflow/manifests//apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- https://github.com/kubeflow/manifests//apps/volumes-web-app/upstream/overlays/istio
# # Tensorboards Controller
# - https://github.com/kubeflow/manifests//apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# # Tensorboard Web App
# - https://github.com/kubeflow/manifests//apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# # Training Operator
# - https://github.com/kubeflow/manifests//apps/training-operator/upstream/overlays/kubeflow
# # MPI Operator
# - https://github.com/kubeflow/manifests//apps/mpi-job/upstream/overlays/kubeflow
# User namespace
- https://github.com/kubeflow/manifests//common/user-namespace/base
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: workflow-controller-configmap
  namespace: kubeflow
  behavior: replace
  files:
  - ./config/config
- name: ml-pipeline-ui-configmap
  behavior: replace
  files:
  - ./config/viewer-pod-template.json
patchesStrategicMerge:
- config/aws-profile-controller-patch.yaml
- config/aws-pipeline-patch.yaml
- config/aws-metadata-patch.yaml
- config/aws-cache-patch.yaml
